services:
  redis:
    restart: always
    image: redis:latest

  nginx:
    restart: always
    image: adithyashenal/milkflow-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf /etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - frontend

  api:
    restart: unless-stopped
    image: adithyashenal/milkflow-api
    environment:
      PORT: 5000
      MONGO_URI: mongodb+srv://washenal55:washenal_admin@mycluster.ja90lnb.mongodb.net/MCLROS?retryWrites=true&w=majority
      NODE_ENV: development
      JWT_SECRET_KEY: MY_SECRET_JWT_KEY
      CVRP_SERVICE_URL: http://cvrp:8080
    depends_on:
      - redis

  frontend:
    image: adithyashenal/milkflow-frontend
    environment:
      OSRM_URL: http://osrm:6000

  cvrp:
    image: adithyashenal/milkflow-cvrp
    restart: always
    environment:
      OSRM_URL: http://osrm:6000

  osrm:
    image: adithyashenal/milkflow-osrm
    container_name: osrm
    ports:
      - "6000:6000"
