services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - ./nginx/default.conf /etc/nginx/conf.d/default.conf
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./Backend
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - ./Backend:/app
    depends_on:
      - redis

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      OSRM_URL: http://osrm:6000

  cvrp:
    build:
      dockerfile: Dockerfile
      context: ./CVRP-service
    environment:
      OSRM_URL: http://osrm:6000

  osrm:
    build:
      dockerfile: Dockerfile.dev
      context: ./Osrm
    container_name: osrm
    ports:
      - "6000:6000"
    volumes:
      - ./osrm/build:/build
