name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          docker build -t adithyashenal/milkflow-frontend ./Frontend
          docker build -t adithyashenal/milkflow-nginx ./nginx
          docker build -t adithyashenal/milkflow-api ./Backend
          docker build -t adithyashenal/milkflow-osrm ./Osrm
          docker build -t adithyashenal/milkflow-cvrp ./CVRP-service

          docker push adithyashenal/milkflow-frontend
          docker push adithyashenal/milkflow-nginx
          docker push adithyashenal/milkflow-api
          docker push adithyashenal/milkflow-osrm
          docker push adithyashenal/milkflow-cvrp
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/milk-flow-production
            git pull origin main

            chmod +x init-letsencrypt.sh

            if [ ! -d "./certbot/conf/live/milkflow.adithyashenal.me" ]; then
              echo "No certificates found. Running initial setup..."
              
              # Ensure firewall allows HTTP/HTTPS
              sudo ufw allow 80/tcp
              sudo ufw allow 443/tcp
              
              # Run the certificate initialization script
              ./init-letsencrypt.sh
            else
              echo "Certificates already exist. Skipping certificate generation."
            fi

            docker compose pull
            docker compose up -d --force-recreate
            docker image prune -f
            docker compose exec nginx nginx -t || echo "Nginx config check failed, but continuing..."
            echo "Deployment completed successfully!"
